import type {Metadata} from "next";
import {Geist, Geist_Mono} from "next/font/google";
import "./globals.css";
import React from "react";
import NavBar from "@/app/components/nav-bar";
import GlobalDialog from "@/app/components/global-dialog";
import {ReactFlowProvider} from "@xyflow/react";
import Auth_provider from "@/app/providers/auth_provider";
import AuthProvider from "@/app/providers/auth_provider";


const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "LLM Dashboard",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en" className="dark">
        <body
            className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
        <AuthProvider>
            <GlobalDialog/>
            <ReactFlowProvider>
                <NavBar/>
                <main>{children}</main>
            </ReactFlowProvider>
        </AuthProvider>
        </body>
        </html>
    );
}
