import type {Metadata} from "next";
import {Geist, Geist_Mono} from "next/font/google";
import "./globals.css";
import React from "react";
import Link from "next/link";
import NavBar from "@/app/components/nav-bar";
import GlobalDialog from "@/app/components/global-dialog";
import {ReactFlowProvider} from "@xyflow/react";



const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "LLM Dashboard",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en" className="dark">
        <GlobalDialog/>
        <ReactFlowProvider>
        <body
            className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >

        <NavBar/>
        <main>{children}</main>
        </body>
        </ReactFlowProvider>
        </html>
    );
}
